[43기 김승태] 장바구니 삭제 기능 구현
wecode-bootcamp-korea/43-1st-soleMates-backend pull request #10
Opened 2023-03-15 08:55 UTC by Dohangang

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- email, password를 이용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- API 호출 시 필요한 값들에 대한 유효성 검사 (예시)

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-03-15 09:51 UTC, kyeongraekim requested changes

2023-03-15 09:51 UTC, kyeongraekim commented on api/controllers/cartController.js
> +  return res.status(200).json({ message: `SUCCESSFULLY_DELETE_CART` });
- delete에 대한 내용은 400과 404의 용례가 교차해서 사용될 수 있습니다. 성공적인 개별 상품에 대한 삭제는 204, no content 메세지 전달이 더 옳을 수 있는데 아래 링크를 참고해주세요!
- [REST Response Code for DELETE Operation, 200 or 204 ?](https://medium.com/@sameira/rest-response-code-for-delete-operation-200-or-204-ee9c72a2dcb2)

2023-03-15 11:12 UTC, kyeongraekim requested changes

2023-03-15 11:12 UTC, kyeongraekim commented on api/controllers/cartController.js
> +  return res.status(204).json({ message: `SUCCESSFULLY_DELETE_CART` });
- 204에 대한 상태코드는 http 통신 특성상 뒤에 오는 메세지를 전달하지 못합니다.
- 해당 내용을 포스트맨을 통해서 한 번 시험해보세요!

2023-03-16 02:53 UTC, Jon9Beom commented on api/controllers/cartController.js
> +  const { cartId } = req.body;
```suggestion
  const { cartId } = req.query;
```

2023-03-16 02:53 UTC, Jon9Beom commented on api/models/cartDao.js
> +    `,
```suggestion
    `DELETE FROM carts
    WHERE id IN (?)
    `,
```

2023-03-16 05:55 UTC, Jon9Beom commented
LGTM 👍

2023-03-16 05:55 UTC, merged