[43기 최원식] 전체상품 리스트 출력
wecode-bootcamp-korea/43-1st-soleMates-backend pull request #6
Opened 2023-03-13 07:22 UTC by Choiwonsikk

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ O ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- email, password를 이용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 상품 전체 리스트 출력

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-03-13 09:51 UTC, Jon9Beom commented on api/routes/productRouter.js
> +router.get("/", productController.productList);
```suggestion
router.get("", productController.productList);
```
REST API에서는 uniform interface 원칙에 따라 엔드포인트 끝에 (`/`)가 들어가는 것을 지양하고 있습니다!

2023-03-13 09:51 UTC, Jon9Beom commented on api/controllers/productController.js
> +});
catchAsync를 활용하고 있기 때문에 지금의 코드에서는 기본적으로 try catch 문이 필요하지 않습니다.
```suggestion
const productList = catchAsync(async (req, res) => {
  const { categoryId, size, color } = req.query;
  
  const list = await productService.productList(categoryId, size, color);
  
  return res.status(200).json({
    data: list,
  });
});
```

2023-03-13 09:51 UTC, Jon9Beom commented on api/models/productDao.js
> +};
```suggestion
const productList = async (categoryId, size, color) => {
  return dataSource.query(
    `SELECT
            p.name as product_name,
            p.price as product_price,
            pi.image_url as product_image,
            l.id as product_likes
        FROM products as p
        LEFT JOIN likes as l ON p.id = l.product_id
        LEFT JOIN product_images as pi ON p.id = pi.product_id
        `
  );
};
```
1. await가 필요없는 코드입니다 :)
2. likes의 의도는, 사람들이 좋아요를 누른 총 개수를 표기하기 위함인가요, 아니면 로그인한 유저가 좋아요를 누른 여부를 판단하기 위함인가요?
3. likes는 데이터가 있을 수도, 없을 수도 있기 때문에 LEFT JOIN을 활용하는 것이 용이하나, product_images를 LEFT JOIN한 이유가 있나요? 이미지도 없는 경우가 있을 수 있기 때문인가요?? (프로젝트 기획을 정확히 알지 못해 여쭤봅니다!)
4. 금일 진행되었던 쿼리빌더 세션의 예시 코드를 참고하여 dynamic filtering 기능을 마저 구현해보셨으면 좋겠습니다!

2023-03-13 10:15 UTC, Choiwonsikk commented on api/models/productDao.js
> +};
likes는 좋아요 기능을 추가하려다가 빼기로 해서 뺄 예정입니다!

그리고 추가로 필터 기능도 추가해서 PR 올리겠습니다~

2023-03-14 11:14 UTC, kyeongraekim requested changes

2023-03-14 11:14 UTC, kyeongraekim commented on api/controllers/productController.js
> +const ALLproductList = catchAsync(async (req, res) => {
- 클래스가 아닌 함수명은 소문자로 시작하고, 캐멀 케이스를 유지하는 것이 node.js 에 기반한 프로그래밍의 네이밍 컨벤션입니다.

2023-03-14 11:14 UTC, kyeongraekim commented on api/models/productDao.js
> +  console.log(categorycondition);
- 상용화될 코드에 불필요한 콘솔로깅은 삭제해주세요!

2023-03-14 11:14 UTC, kyeongraekim commented on api/models/productDao.js
> +  }
- 해당 내용은 if-else의 조건분기보다 더 속도, 가독성면에서 효율적인 switch-case문으로의 1차 리팩토링을 고려해보세요!
- 아래 내용을 참고해서 접근해보세요! 만일 내일 오후 선까지 리팩토링이 힘드실 것 같으면 제게 디엠 주시거나 이곳 코멘트로 글을 남겨주세요!~

```javascript
const { categoryDao } = require('../models');

const categoryService = async(categoryId, offset, limit, minPrice, maxPrice, sortBy) => {

    const ordering = async(sortBy) => {

        switch(sortBy){
            case 'priceASC':
                return `ORDER BY o.price ASC, o.id ASC`
            case 'priceDESC':
                return `ORDER BY o.price DESC, o.id ASC`
            case 'nameASC':
                return `ORDER BY productName ASC, o.id ASC`
            case 'newest':
                return `ORDER BY p.created_at DESC, o.id ASC`
            default:
                return `ORDER BY o.id`
        }
    };

    const priceRange = async(minPrice, maxPrice) => {

        if (!minPrice && !maxPrice) return ` AND o.price>=0`

        if (minPrice===0)           return ` AND (o.price>=0 AND o.price<${maxPrice})`

        return  ` AND (o.price>=${minPrice} AND o.price<${maxPrice})`;

    };

    const orderingQuery = await ordering(sortBy);
    const priceRangeQuery = await priceRange(minPrice, maxPrice);

    return await categoryDao.getProductsByCat(categoryId, offset, limit, orderingQuery, priceRangeQuery);
}

module.exports = {
    categoryService
}

2023-03-15 00:50 UTC, Choiwonsikk commented on api/models/productDao.js
> +  }
리팩토링은 세부리스트까지 구현한 다음에 시간적 여유가 있을 때 하겠습니다

2023-03-15 01:30 UTC, kyeongraekim commented
원식님 컨플릭트 해결 부탁드립니다!~

2023-03-15 01:54 UTC, Choiwonsikk commented
> 원식님 컨플릭트 해결 부탁드립니다!~  productService,
해결 완료 했습니다!

2023-03-15 02:24 UTC, kyeongraekim approved these changes
LGTM!~

2023-03-15 02:24 UTC, merged